import { Inter } from "@next/font/google"
import Head from "next/head"
import { useRef, useState } from "react"
import { toast } from "react-hot-toast"

const inter = Inter({ subsets: ["latin"] })

export default function Home() {
  const inputRef = useRef<HTMLInputElement>(null)
  const [output, setOutput] = useState<string | null>("yes")

  const runQuery = () => {
    toast.loading("Fetching...")
    const query = inputRef.current?.value

    if (!query) return

    // run the query
  }

  return (
    <>
      <Head>
        <title>GPT Openai Example</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="w-full flex items-center flex-col justify-center min-h-[48rem] h-full">
        <h1 className="text-2xl font-bold font-sans">
          What kind of work do you do?
        </h1>

        <div className="min-w-[24rem]">
          <input
            ref={inputRef}
            className="mt-8 outline-none border text-sm rounded-lg block w-full p-2.5 focus:ring-blue-500 focus:ring-2  !bg-gray-700 !border-gray-600 !placeholder-gray-400 !text-white !focus:ring-blue-500 !focus:border-blue-500"
          />
        </div>

        <button
          onClick={runQuery}
          className="
        text-white bg-blue-600 hover:bg-blue-700 focus:ring-4 !focus:ring-blue-800 font-medium rounded-lg text-base px-6 py-2.5 text-center mt-4 md:mb-0 inline-flex items-center justify-center"
        >
          Get me that job!
        </button>

        {output && (
          <div className="p-8 rounded-lg bg-black/10 border-black/25 border-2 mt-12 w-full max-w-[30%] text-gray-100">
            This is the output
          </div>
        )}
      </main>{" "}
    </>
  )
}
